# 탐색과 정렬

## Problem 7
### Problem 7.1

<br>

```python
def search_list(a, x):
  n = len(a)
  for i in range(0,n):
    if x == a[i]:
      return i

  return -1

v = [17, 92, 18, 33, 58, 7, 33, 42]
print(search_list(v,18)) # 2
print(search_list(v,33)) # 3
print(search_list(v,900)) # -1
```

<br>프로그램 7-1은 리스트에 찾는 값이 여러개 있더라도 첫번째 위치만 결과로 돌려줍니다. 
<br>찾는 값이 나오는 모든 위치를 리스트로 돌려주는 탐색 알고리즘을 만들어 보세요. 
<br>찾는 값이 리스트에 없다면 빈 리스트인 []를 돌려줍니다.

In [1]:
from timeit import timeit


def search_list(array: list, x):

    return [idx for (idx, element) in enumerate(array) if element == x]


v = [17, 92, 18, 33, 58, 7, 33, 42]
print(search_list(v, 18))  # [2]
print(search_list(v, 33))  # [3, 6]
print(search_list(v, 900))  # []

print(timeit(
    stmt='search_list(v, 33)',
    setup='from __main__ import search_list, v',
    number=1))


[2]
[3, 6]
[]
4.251998689142056e-06


### Problem 7.2

<br>연습 문제 `7-1` 프로그램의 계산 복잡도는 무엇일까요?

<br> -> $O(n)$

### Problem 7.3

<br>다음과 같이 학생 번호와 이름이 리스트로 주어졌을 때 학생번호를 입력하면 학생번호에 해당하는 이름을 순차 탐색으로 찾아 돌려주는 함수를 만들어 보세요. 
<br>해당하는 학생 번호가 없으면 물음표(?)를 돌려줍니다. 
<br>참고로 학생 번호가 39번이면 'Justin', 14번이면 'John'을 돌려줍니다.
<br>
```
stu_no = [39, 14, 67, 105]
stu_name = ["Justin", "John", "Mike", "Summer"]
```


In [2]:
from timeit import timeit


stu_no = [39, 14, 67, 105]
stu_name = ["Justin", "John", "Mike", "Summer"]


def find_stu(stu_no: list, stu_name: list, number: int):

    for no, name in zip(stu_no, stu_name):
        if no == number:
            return name
    return "?"


print(find_stu(stu_no, stu_name, 67))
print(find_stu(stu_no, stu_name, 19))
print(timeit(
    stmt='find_stu(stu_no, stu_name, 67)',
    setup='from __main__ import find_stu, stu_no, stu_name',
    number=1
))


Mike
?
2.299000698258169e-06


## Problem 8
### Problem 8.1

<br>일반적인 선택 정렬 알고리즘을 사용해서 리스트 `[2, 4, 5, 1, 3]` 을 정렬하는 과정을 적어 보세요.

In [3]:
from timeit import timeit


def sel_sort_ascending_order(array: list):

    for i in range(len(array)-1):
        min_idx = i
        for j in range(i+1, len(array)):
            if array[j] < array[min_idx]:
                min_idx = j
        array[i], array[min_idx] = array[min_idx], array[i]
    return array


a = [2, 4, 5, 1, 3]
print(sel_sort_ascending_order(a))
print(timeit(
    stmt='sel_sort_ascending_order(a)',
    setup='from __main__ import sel_sort_ascending_order, a',
    number=1
))


[1, 2, 3, 4, 5]
7.188999006757513e-06


### Problem 8.2

<br> 

```python
# Program 8-1
# 쉽게 설명한 선택 정렬
# 입력: 리스트 a
# 출력: 정렬된 새 리스트

# 주어진 리스트에서 최솟값의 위치를 돌려주는 함수
def find_min_idx(a):
    n = len(a)
    min_idx = 0
    for i in range(1, n):
        if a[i] < a[min_idx]:
            min_idx = i
    return min_idx

def sel_sort(a):
    result = []  # 새 리스트를 만들어 정렬된 값을 저장
    while a:     # 주어진 리스트에 값이 남아있는 동안 계속
        min_idx = find_min_idx(a)  # 리스트에 남아 있는 값 중 최솟값의 위치
        value = a.pop(min_idx)    # 찾은 최솟값을 빼내어 value에 저장
        result.append(value)     # value를 결과 리스트 끝에 추가
    return result

d = [2, 4, 5, 1, 3]
print(sel_sort(d))

# Program 8-2
# 내림차순 선택 정렬
# 입력: 리스트 a
# 출력: 없음(입력으로 주어진 a가 정렬됨)

def sel_sort(a):
    n = len(a)
    for i in range(0, n - 1):
        max_idx = i  # 최솟값(min) 대신 최댓값(max)을 찾아야 함
        for j in range(i + 1, n):
            if a[j] > a[max_idx]:  # 부등호 방향 뒤집기
                max_idx = j
        a[i], a[max_idx] = a[max_idx], a[i]

d = [2, 4, 5, 1, 3]
sel_sort(d)
print(d)
```

<br>프로그램 8-1과 8-2의 정렬 알고리즘은 숫자를 작은 수에서 큰 수 순서로 나열하는 오름차순 정렬이었습니다.
<br>이 알고리즘을 큰 수에서 작은 수 순서로 나열하는 내림차순 정렬로 바꾸려면 프로그램의 어느 부분을 바꿔야 할까요?

**TIP**: 오름차순과 내림차순 정렬 예

- 오름차순 정렬의 예: 가나다순, 쇼핑몰에서 낮은 가격순으로 보기
- 내림차순 정렬의 예: 시험 점수로 등수 구하기, 최신 뉴스부터 보기

**정답**
최소값의 index를 찾는 과정을 최대값의 index를 찾는 과정으로 바꾸면 된다.

In [4]:
from timeit import timeit


def sel_sort_descending_order(array: list):

    for i in range(len(array)-1):
        max_idx = i
        for j in range(i+1, len(array)):
            if array[j] > array[max_idx]:
                max_idx = j
        array[i], array[max_idx] = array[max_idx], array[i]
    return array


a = [2, 4, 5, 1, 3]
print(sel_sort_descending_order(a))
print(timeit(
    stmt='sel_sort_descending_order(a)',
    setup='from __main__ import sel_sort_descending_order, a',
    number=1
))


[5, 4, 3, 2, 1]
6.4449995988979936e-06


## Problem 9

<br>일반적인 삽입 정렬 알고리즘을 사용해서 리스트 `[2, 4, 5, 1, 3]` 을 정렬하는 과정을 적어 보세요.

In [5]:
from timeit import timeit


def ins_sort_ascending_order(array: list):

    for i in range(1, len(array)):
        element = array[i]
        j = i-1
        while j >= 0 and array[j] > element:
            array[j+1] = array[j]
            j -= 1
        array[j+1] = element
    return array


a = [2, 4, 5, 1, 3]
print(ins_sort_ascending_order(a))
print(timeit(
    stmt='ins_sort_ascending_order(a)',
    setup='from __main__ import ins_sort_ascending_order, a',
    number=1
))


[1, 2, 3, 4, 5]
3.4360000427113846e-06


### Problem 9.2

<br>문제 9에서 설명한 정렬 알고리즘은 숫자를 작은 수에서 큰 수 순서로 나열하는 오름차순 정렬이었습니다. 
<br>이를 큰 수 에서 작은 수 순서로 나열하는 내림차순 정렬로 바꾸려면 프로그램의 어느 부분을 바꿔야 할까요?

In [6]:
from timeit import timeit


def ins_sort_descending_order(array: list):

    for i in range(1, len(array)):
        element = array[i]
        j = i-1
        while j >= 0 and array[j] < element:
            array[j+1] = array[j]
            j -= 1
        array[j+1] = element
    return array


a = [2, 4, 5, 1, 3]
print(ins_sort_descending_order(a))
print(timeit(
    stmt='ins_sort_descending_order(a)',
    setup='from __main__ import ins_sort_descending_order, a',
    number=1
))


[5, 4, 3, 2, 1]
3.817000106209889e-06


## Problem 10
### Problem 10.1

<br>

```python
# Program 10-2
# 병합 정렬
# 입력: 리스트 a
# 출력: 없음(입력으로 주어진 a가 정렬됨)

def merge_sort(a):
    n = len(a)
    # 종료 조건: 정렬할 리스트의 자료 개수가 한 개 이하이면 정렬할 필요가 없음
    if n <= 1:
        return
    # 그룹을 나누어 각각 병합 정렬을 호출하는 과정
    mid = n // 2  # 중간을 기준으로 두 그룹으로 나눔
    g1 = a[:mid]
    g2 = a[mid:]
    merge_sort(g1)  # 재귀 호출로 첫 번째 그룹을 정렬
    merge_sort(g2)  # 재귀 호출로 두 번째 그룹을 정렬
    # 두 그룹을 하나로 병합
    i1 = 0
    i2 = 0
    ia = 0
    while i1 < len(g1) and i2 < len(g2):
        if g1[i1] < g2[i2]:
            a[ia] = g1[i1]
            i1 += 1
            ia += 1
        else:
            a[ia] = g2[i2]
            i2 += 1
            ia += 1
    # 아직 남아 있는 자료들을 결과에 추가
    while i1 < len(g1):
        a[ia] = g1[i1]
        i1 += 1
        ia += 1
    while i2 < len(g2):
        a[ia] = g2[i2]
        i2 += 1
        ia += 1

d = [6, 8, 3, 9, 10, 1, 2, 4, 7, 5]
merge_sort(d)
print(d)
```

<br>프로그램 10-2에서 다룬 정렬 알고리즘은 숫자를 작은 수에서 큰 수 순서로 나열하는 오름차순 정렬이었습니다. 
<br>오른차순 정렬을 큰 수에서 작은 수 순서로 나열하는 내림차순 정렬로 바꾸려면 프로그램의 어느 부분을 바꿔야 할까요? 

In [9]:
import numpy as np
from timeit import timeit


def merge_sort_descending(array: list):

    if len(array) <= 1:
        return

    mid = len(array) // 2
    g1 = array[:mid].copy()
    g2 = array[mid:].copy()
    g_idx1 = 0
    g_idx2 = 0
    array_idx = 0

    merge_sort_descending(g1)
    merge_sort_descending(g2)

    def insert(array_idx: int, g: list, g_idx: int):
        array[array_idx] = g[g_idx]
        g_idx += 1
        array_idx += 1
        return array_idx, g_idx

    while g_idx1 < len(g1) and g_idx2 < len(g2):
        if g1[g_idx1] > g2[g_idx2]:
            array_idx, g_idx1 = insert(array_idx, g1, g_idx1)
        else:
            array_idx, g_idx2 = insert(array_idx, g2, g_idx2)
    while g_idx1 < len(g1):
        array_idx, g_idx1 = insert(array_idx, g1, g_idx1)
    while g_idx2 < len(g2):
        array_idx, g_idx2 = insert(array_idx, g2, g_idx2)


def merge_sort(a):
    n = len(a)
    if n <= 1:
        return
    mid = n // 2
    g1 = a[:mid]
    g2 = a[mid:]
    merge_sort(g1)
    merge_sort(g2)
    i1 = 0
    i2 = 0
    ia = 0
    while i1 < len(g1) and i2 < len(g2):
        if g1[i1] > g2[i2]:
            a[ia] = g1[i1]
            i1 += 1
            ia += 1
        else:
            a[ia] = g2[i2]
            i2 += 1
            ia += 1
    while i1 < len(g1):
        a[ia] = g1[i1]
        i1 += 1
        ia += 1
    while i2 < len(g2):
        a[ia] = g2[i2]
        i2 += 1
        ia += 1


array = np.arange(10000)
np.random.shuffle(array)

print('time cost of merge sort')
print(timeit(
    stmt='merge_sort_descending(array)',
    setup='from __main__ import merge_sort_descending, array',
    number=1
))
print(array)

print('-'*25)

np.random.shuffle(array)
print('time cost of selection sort')
print(timeit(
    stmt='sel_sort_descending_order(array)',
    setup='from __main__ import sel_sort_descending_order, array',
    number=1
))
print(sel_sort_descending_order(array))

print('-'*25)

np.random.shuffle(array)
print('time cost of insert sort')
print(timeit(
    stmt='ins_sort_descending_order(array)',
    setup='from __main__ import ins_sort_descending_order, array',
    number=1
))
print(ins_sort_descending_order(array))

print('-'*25)

np.random.shuffle(array)
print('time cost of program 10-2')
print(timeit(
    stmt='merge_sort(array)',
    setup='from __main__ import merge_sort, array',
    number=1
))
print(array)


time cost of merge sort
0.1207545930010383
[9999 9998 9997 ...    2    1    0]
-------------------------
time cost of selection sort
13.791666537999845
[9999 9998 9997 ...    2    1    0]
-------------------------
time cost of insert sort
9.054392526000811
[9999 9998 9997 ...    2    1    0]
-------------------------
time cost of program 10-2
0.0711663590009266
[9999 9999 9999 ... 3734 3734 1094]


## Problem 11
### Problem 11.1

<br>지금까지 배운 네 가지 정렬 알고리즘 말고도 훨씬 많은 정렬 알고리즘이 있습니다. 
<br>그 중 하나인 거품 정렬(Bubble sort)을 줄 서기로 비유하면 다음과 같습니다. 
<br>다음 과정을 읽고 리스트 `[2, 4, 5, 1, 3]`이 정렬되는 과정을 알고리즘으로 적어보세요.

In [10]:
import numpy as np
from timeit import timeit


def bubble_sort_ascending(array: list):

    while True:

        change = False

        for idx in range(len(array)-1):

            if array[idx] > array[idx+1]:
                array[idx], array[idx+1] = array[idx+1], array[idx]
                change = True

        if not change:
            break

    return array


def bubble_sort_descending(array: list):

    while True:

        change = False

        for idx in range(len(array)-1):

            if array[idx] < array[idx+1]:
                array[idx], array[idx+1] = array[idx+1], array[idx]
                change = True

        if not change:
            break

    return array


array = np.arange(10000)
np.random.shuffle(array)
print(timeit(
    stmt='bubble_sort_ascending(array)',
    setup='from __main__ import bubble_sort_ascending, array',
    number=1
))
print(array)

print('-'*25)

np.random.shuffle(array)
print(timeit(
    stmt='bubble_sort_descending(array)',
    setup='from __main__ import bubble_sort_descending, array',
    number=1
))
print(array)


37.20364860900008
[   0    1    2 ... 9997 9998 9999]
-------------------------
37.29197494999971
[9999 9998 9997 ...    2    1    0]


## Problem 12
### Problem 12.1

<br> 다음 과정을 참고하여 재귀 호출을 사용한 이분 탐색 알고리즘을 만들어 보세요.
<br>

1. 주어진 탐색 대상이 비어 있다면 탐색할 필요가 없습니다. (종료 조건)
2. 찾는 값과 주어진 탐색 대상의 중간 위치 값을 비교합니다.
3. 찾는 값과 중간 위치 값이 같다면 결과값으로 중간 위치 값을 돌려줍니다.
4. 찾는 값이 중간 위치 값보다 크다면 중간 위치의 오른쪽을 대상으로 이분 탐색 함수를 재귀 호출합니다.
5. 찾는 값이 중간 위치 값보다 작다면 중간 위치의 왼쪽을 대상으로 이분 탐색 함수를 재귀 호출합니다.

In [12]:
import numpy as np
from timeit import timeit


def binary_search_recursive(array: list, value: int):

    if not array:
        return -1

    center_idx = len(array) // 2

    if value == array[center_idx]:
        return array[center_idx]
    elif value > array[center_idx]:
        return binary_search_recursive(array[center_idx+1:], value)
    else:
        return binary_search_recursive(array[:center_idx], value)


def binary_search_for(array: list, value: int):

    start_idx, center_idx, end_idx = 0, len(array) // 2, len(array)

    while end_idx - start_idx > 1:
        if value > array[center_idx]:
            start_idx = center_idx
        else:
            end_idx = center_idx
        center_idx = (start_idx+end_idx) // 2

    if value == array[start_idx] or value == array[end_idx]:
        return value
    else:
        return -1


array = sorted(
    np.random.choice(np.arange(1000), size=500, replace=False).tolist())
value = np.random.randint(low=0, high=1000)

print(timeit(
    stmt='binary_search_recursive(array, value)',
    setup='from __main__ import binary_search_recursive, array, value',
    number=1
))
print(f"Find {value} index in array with recursive: "
      f"{binary_search_recursive(array, value)}")

print('-'*25)

print(timeit(
    stmt='binary_search_for(array, value)',
    setup='from __main__ import binary_search_for, array, value',
    number=1
))
print(f"Find {value} index in array with for loop: "
      f"{binary_search_for(array, value)}")


1.4824996469542384e-05
Find 72 index in array with recursive: 72
-------------------------
8.022998372325674e-06
Find 72 index in array with for loop: 72
